### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Sispheor** [ownaginatious/amqp-client-cli#1]
Hi, here is my output with the command line from your example.
```
 amqpcli send 127.0.0.1 5672 exchange_a simple_message -m "Hello there" -v vhost -s
```
```
Traceback (most recent call last):
  File "/usr/local/bin/amqpcli", line 11, in <module>
    load_entry_point('amqp-client-cli==0.2.post3', 'console_scripts', 'amqpcli')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/amqp_client_cli/main.py", line 106
    print("Connecting to queue @ %s:%s... " % (host, port), end="")
```

**Comment by ownaginatious** [comment]
Hi there! Thanks for reporting this. I believe I have fixed the issue in version `0.2.post5`. Please try that and let me know if it resolves things for you :)
