### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cbalmeida** [ownaginatious/amqp-client-cli#6]
Any suggestion?

c2@ubuntu:~$ amqpcli config --help

Traceback (most recent call last):
  File "/usr/local/bin/amqpcli", line 11, in <module>
    load_entry_point('amqp-client-cli==0.4.1', 'console_scripts', 'amqpcli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/c2/.local/lib/python2.7/site-packages/amqp_client_cli/main.py", line 34
    user = input(f"{Fore.GREEN}User: {Fore.RESET}")
                                                 ^
SyntaxError: invalid syntax

**Comment by ownaginatious** [comment]
You appear to be using python 2. This is only compatible with python 3.
